### ISSUE TITLE
correction in wiki "void playFolderTrack" section

### ISSUE THREAD

**Issue by shariramani** [Makuna/DFMiniMp3#12]
In following lines playMp3FolderTrack(2, 13)  should be replaced with playFolderTrack(2, 13).

void playFolderTrack(uint8_t folder, uint8_t track)
This will play the track from within the specific numbered folder.
An example filename would be sd:/002/013_ThisIsMyFavoriteSong.mp3, and calling playMp3FolderTrack(2, 13) would play it.

**Comment by Makuna** [comment]
Fixed.
Note:  You should be able to edit the Wiki directly.  If I don't like changes I can always revert it; but most people are pretty good at doing the right thing.
