### ISSUE TITLE
What does void loop() do, what's its purpose?

### ISSUE THREAD

**Issue by roundbananas** [Makuna/DFMiniMp3#15]
Hi Makuna
Thank you for this library. Very helpful.
I'm unclear what the purpose of  void loop() is. What do you mean "this will service the DFMiniMP3"? 
It doesn't seem to matter that I didn't include it in my sketch. But I'm wondering if I need to?

cheers
Carl

**Comment by Makuna** [comment]
Issues are not for asking questions; it is for tracking bugs in this library.

Both the readme and the wiki point to the gitter channel (https://gitter.im/DFMiniMp3/Lobby) where you can ask questions.
