### ISSUE TITLE
File/Format parser for DFplayer Mini

### ISSUE THREAD

**Issue by Schallbert** [Makuna/DFMiniMp3#27]
I have written a script to have M3U playlist files parsed and the MP3 files copied into a folder structure, renamed in a way that it can be directly read by DFplayer mini.
It has nothing to do with your library but I thought it may come in handy.
Pls have a look at https://github.com/Schallbert/DFplayer_AutoStructureFromPlaylist
to see whether you can take advantage of this script.
Regards, 
Schallbert

**Comment by Makuna** [comment]
If you want, add a link to your work in the Wiki [here](https://github.com/Makuna/DFMiniMp3/wiki#projects-that-use-this-library)

**Comment by Schallbert** [comment]
Updated the Wiki as recommended. 
Win10 x64 .exe now also available on project.
Closing issue.
