### ISSUE TITLE
Wake up after sleep with setPlaybackSource

### ISSUE THREAD

**Issue by accidentalrebel** [Makuna/DFMiniMp3#31]
Not exactly an issue but I've read your note in the wiki that says the only way you know how to wake up is using reset()

> Note: currently the only way to wake up the module that I know of is with reset(); but this is a slow process and may cause click noises in the audio output.

I learned from [this library](https://github.com/PowerBroker2/DFPlayerMini_Fast) that you can initiate a wake up by setting the play source to SD. In our case it can be done by calling:

>  setPlaybackSource(DfMp3_PlaySource_Sd);

I tried it and it worked. It seems to reset the player but it's quick and does not have a click noise that you noted. 

Not sure if this is the best approach but it worked for me. Just thought you should know.

**Comment by Makuna** [comment]
You can go ahead and add that to the wiki.  I will give it a try.

Thanks

**Comment by accidentalrebel** [comment]
Hi. I think I need to be added as contributor to have editing privileges on the wiki.

I can add my project too on the **Projects that use this library section.**

**Comment by seisfeld** [comment]
I can confirm, the Wiki seems not editable.

**Comment by Makuna** [comment]
For some reason it got switched to collaborators only. I believe that Wikis should be open and it always gives me the chance to revert what others do anyhow.  

It should now allow you to edit.

**Comment by seisfeld** [comment]
Yap it’s editable now! Thanks @Makuna. 👍🏻

**Comment by accidentalrebel** [comment]
I updated the wiki. Since I'm the only one who was confirmed that my approach is working I updated the note to say that we have two confirmed methods.

> Note:
There are two confirmed ways to wake up a module. Try any of the two and see which works best for your particular hardware:
>   * Calling reset(), although this is a slow process and may cause click noises in the audio output
>   * Calling setPlaybackSource(DfMp3_PlaySource_Sd)

If @Makuna  can confirm then that would be great.

**Comment by ghmartin77** [comment]
Please note #37. Might have an impact on this one if fixed. I don't suppose it has, but should be checked, if the fix is applied, though.

**Comment by Makuna** [comment]
New release exposes it.
