### ISSUE TITLE
Please Add enableLoop and disableLoop

### ISSUE THREAD

**Issue by busel7** [Makuna/DFMiniMp3#45]
Hi, thanks for your great library, I used a number of additional features in my project, glad that these additions could go into the main repository.

```
// CUSTOM
    void enableLoop() {
	sendPacket(0x19, 0x00);
    }

    void disableLoop() {
	sendPacket(0x19, 0x01);
    }
// END CUSTOM
```

Thank you very much

**Comment by Makuna** [comment]
To follow the API standards (see setRepeatPlay), it would be slightly different.
```
    void setCurrentTrackRepeatPlay(bool repeat)
    {
        sendPacket(0x19, !repeat);
    }
```

**Comment by Makuna** [comment]
https://github.com/Makuna/DFMiniMp3/pull/46

**Comment by busel7** [comment]
Nice, thank you :).
