### ISSUE TITLE
Feature request: Loop random tracks from folder

### ISSUE THREAD

**Issue by marrobHD** [Makuna/DFMiniMp3#50]
Please add a feature which we are able to loop a folder an play random track in it.
Something like `loopFolderrandom(1, 1-3)`

**Comment by seisfeld** [comment]
I'd consider this a high level function which one need to take care for and implement yourself in the parent sketch. This would require the library to keep track of sort of a playlist which is not it's duty - IMHO.

**Comment by marrobHD** [comment]
I tried 
```
randNumber = random(1, 3);
mp3.playFolderTrack(1, randNumber)
```
but it wont work

**Comment by seisfeld** [comment]
There is the play random example. You can modify that one to play a specific folder or a specific file in a folder. Then hook into `OnPlayFinished()` to play the next track.

**Comment by marrobHD** [comment]
That wont work for me. I want to play a random track from only one folder and not all.

**Comment by Makuna** [comment]
@marrobHD Issues are not meant to be a place to ask questions or seek general help.  It is meant to be a place to "register" an issue.  The original feature request was valid, but as stated can't be done in the library.  The chip doesn't support it and it requires knowledge that the library could never have to implement it.

If you wish support, please use the gitter channel (see readme and wiki for pointers).
