### ISSUE TITLE
Nothing is read after nextTrack ()

### ISSUE THREAD

**Issue by Gerggg** [Makuna/DFMiniMp3#52]
Hello,
When I use the nextTrack() method, once the new MP3 is finished, nothing happens.
How do I get the next MP3 to play automatically?

thank you so much
Greg

**Comment by Makuna** [comment]
Issues are for bugs in the library, not for general use questions.  Please jump on gitter and we can answer questions there.

Check the readme or the wiki for the link to gitter.

**Comment by Gerggg** [comment]
Thanks for nothing, I'm going to look for another library that works properly
