### ISSUE TITLE
Suggestion: Add serial speed as parameter to .begin()

### ISSUE THREAD

**Issue by seisfeld** [Makuna/DFMiniMp3#53]
Hey @Makuna do you think its possible to make the serial speed a parameter to `.begin()`? I know the chip is fixed to 9600 but for debugging purposes and to support other chips with different speed but similar interface it would be helpful. Currently the speed change needs to be done directly in DFMiniMp3.h but doing `mp3.begin(2400);` or whatever would be nice.

I forgot to mention, it would be nice if it were optional with 9600 as default. So it would not break existing sketches.

**Comment by Makuna** [comment]
https://github.com/Makuna/DFMiniMp3/pull/54
