### ISSUE TITLE
Suggestion: Add Mp3Notify.h to source

### ISSUE THREAD

**Issue by Cemil97** [Makuna/DFMiniMp3#55]
The Mp3Notify class from the examples is likely used by most as is. Suggest adding it to the source as Mp3Notify.h to provide a default implementation "out of the box".

**Comment by Makuna** [comment]
Thanks for making a suggestion.  Generally I would prefer these be "talked about" through gitter first as Issues is for bugs or tracking an enhancement.

Actually, I would hope it would not be used by default.  Its an example and handy for debug is all.  

Making that change makes an assumption you have two UARTs or that you have the debug uart and software serial for the MP3 chips.   These are not thins I want to promote.
