### ISSUE TITLE
Controlling two DFMiniMp3 Boards?

### ISSUE THREAD

**Issue by robsworld** [Makuna/DFMiniMp3#7]
Hi,
is it possible to control two boards with one Arduino with this library? 
I tried this with the original library of the DF Boards, but it doesn't work :-(
Robert

**Comment by Makuna** [comment]
It all depends on how much serial support you have on your Arduino.   Just supply unique serial objects for each mp3 board like below and it should work fine.
```
DFMiniMp3<HardwareSerial, Mp3NotifyOne> mp3One(Serial1);
DFMiniMp3<HardwareSerial, Mp3NotifyTwo> mp3Two(Serial2);
```

**Comment by robsworld** [comment]
Great! I got it. Worked fine :-) 
Thank you!
