### ISSUE TITLE
How repeat current track?

### ISSUE THREAD

**Issue by massimo2021** [Makuna/DFMiniMp3#76]
Hi  :-)
Please, can you show us how to write, in an Arduino sketch, the right code  to repeat current track?
I'm not a programmer and don't understand the line from DFMiniMp3.h  _void setRepeatPlayCurrentTrack(bool repeat)_

Thanks

Massimo

( DFPLayer with chip MH2024K-16SS )

**Comment by Schallbert** [comment]
Hi Massimo.
First, this is not the right place for your inquiry,  the "issues" tab should only be used for bug reports etc. Please move this to "DISCUSSIONS".
Use the Wiki https://github.com/Makuna/DFMiniMp3/wiki/API-Reference#void-setrepeatplayallinrootbool-repeat
to understand which function does what. When you e.g. write 
`dfmini.setRepeatPlayCurrentTrack(true);`
And then have your song played e.g. using playFolderTrack, this song should be repeating. 
You'll need some time to experiment with your hardware, play around with function calls in this library  etc. that's the best way to learn.

**Comment by massimo2021** [comment]
Well. 
Thanks for the advice  :-)
