### ISSUE TITLE
get current track filename ?

### ISSUE THREAD

**Issue by pploume** [Makuna/DFMiniMp3#97]
Hi,

Thanks a lot for this usefull library !

Is it possible to get the track playing file name (and then extract the text in the filename to get "myMusic" from filename 0001_myMusic.mp3 ) ?

Could be very cool

**Comment by seisfeld** [comment]
Nope, this is impossible.

**Comment by Makuna** [comment]
As stated, not possible.  The API never exposes file names at all, just track indexes, and even these are inconsistent (002 vs 02) depending on versions.

**Comment by pploume** [comment]
Ok, thanks for the reply.

Le jeu. 25 août 2022, 20:31, Michael Miller ***@***.***> a
écrit :
